name: keras
channels: !!python/tuple
- defaults
dependencies:
- _nb_ext_conf=0.3.0=py35_0
- anaconda-client=1.6.0=py35_0
- appnope=0.1.0=py35_0
- clyent=1.2.2=py35_0
- conda-forge::mock=2.0.0=py35_0
- conda-forge::pbr=1.10.0=py35_0
- conda-forge::protobuf=3.0.0=py35_0
- conda-forge::six=1.10.0=py35_0
- conda-forge::tensorflow=0.11.0=py35_0
- cycler=0.10.0=py35_0
- decorator=4.0.10=py35_1
- entrypoints=0.2.2=py35_0
- freetype=2.5.5=1
- h5py=2.6.0=np111py35_2
- hdf5=1.8.17=1
- https://conda.binstar.org/menpo::opencv3=3.1.0=py35_0
- https://conda.binstar.org/menpo::tbb=4.3_20141023=0
- icu=54.1=0
- ipykernel=4.5.2=py35_0
- ipython=5.1.0=py35_1
- ipython_genutils=0.1.0=py35_0
- ipywidgets=5.2.2=py35_0
- jinja2=2.8=py35_1
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.4.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_core=4.2.1=py35_0
- libpng=1.6.27=0
- markupsafe=0.23=py35_2
- matplotlib=1.5.3=np111py35_1
- mistune=0.7.3=py35_1
- mkl=11.3.3=0
- nb_anacondacloud=1.2.0=py35_0
- nb_conda=2.0.0=py35_0
- nb_conda_kernels=2.0.0=py35_0
- nbconvert=4.2.0=py35_0
- nbformat=4.2.0=py35_0
- nbpresent=3.0.2=py35_0
- notebook=4.3.0=py35_0
- numpy=1.11.2=py35_0
- openssl=1.0.2j=0
- pandas=0.19.2=np111py35_0
- path.py=8.2.1=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.4=py35_0
- pip=9.0.1=py35_1
- prompt_toolkit=1.0.9=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=5.6.0=py35_1
- python=3.5.2=0
- python-dateutil=2.6.0=py35_0
- pytz=2016.10=py35_0
- pyyaml=3.12=py35_0
- pyzmq=16.0.2=py35_0
- qt=5.6.2=0
- qtconsole=4.2.1=py35_1
- readline=6.2=2
- requests=2.12.4=py35_0
- setuptools=27.2.0=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- sqlite=3.13.0=0
- terminado=0.6=py35_0
- tk=8.5.18=0
- tornado=4.4.2=py35_0
- traitlets=4.3.1=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=1.2.6=py35_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - click==6.6
  - enum-compat==0.0.2
  - eventlet==0.20.0
  - flask==0.12
  - greenlet==0.4.11
  - imageio==2.1.2
  - ipython-genutils==0.1.0
  - itsdangerous==0.24
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.1
  - keras==1.2.0
  - moviepy==0.2.2.13
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - pillow==3.4.2
  - prompt-toolkit==1.0.9
  - python-engineio==1.1.0
  - python-socketio==1.6.1
  - scikit-learn==0.18.1
  - scipy==0.18.1
  - theano==0.8.2
  - tqdm==4.10.0
  - werkzeug==0.11.15
prefix: //anaconda/envs/keras

